--- #YAML:1.0
name: AI-Prolog
version: 0.734
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "Perl extension for logic programming."
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
