# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AI-Prolog
version:      0.5
version_from: lib/AI/Prolog.pm
installdirs:  site
requires:
    aliased:                       0.11
    Clone:                         0.15
    Exporter::Tidy:                0.06
    Hash::AsObject:                0.05
    Pod::Usage:                    1.12
    Test::Differences:             0.47
    Test::MockModule:              0.04
    Text::Balanced:                1.95

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
