--- #YAML:1.0
name:                AI-Prolog
version:             0.739
abstract:            Perl extension for logic programming.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    aliased:                       0.11
    Clone:                         0.15
    Exporter::Tidy:                0.06
    Hash::AsObject:                0.05
    Hash::Util:                    0
    Pod::Usage:                    1.12
    Regexp::Common:                2.119
    Scalar::Util:                  0
    Term::ReadKey:                 2.21
    Term::ReadLine:                1.01
    Text::Balanced:                1.95
    Text::Quote:                   0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Curtis "Ovid" Poe
