--- #YAML:1.0
name:                AI-Prolog
version:             0.736
abstract:            Perl extension for logic programming.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    aliased:                       0.11
    Clone:                         0.15
    Exporter::Tidy:                0.06
    Hash::AsObject:                0.05
    Pod::Usage:                    1.12
    Regexp::Common:                2.119
    Scalar::Util:                  0
    Test::Differences:             0.47
    Test::Exception:               0.2
    Test::MockModule:              0.04
    Test::Warn:                    0.08
    Text::Balanced:                1.95
    Text::Quote:                   0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Curtis "Ovid" Poe
